DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
  department_id INT PRIMARY KEY,
  department_name VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLOYEE (
  employee_id INT PRIMARY KEY,
  employee_name VARCHAR(50) NOT NULL,
  salary FLOAT NOT NULL,
  department_id INT
  -- FOREIGN KEY(department_id) REFERENCES DEPARTMENT 
);

